### ISSUE TITLE
Remove local in the version selector in the PG

### ISSUE THREAD

**Issue by deltakosh** [BabylonJS/Babylon.js#12215]
Also make sure the cursor is correctly positioned in the drop down (so far it seems to stay on latest no matter what)

**Comment by RaananW** [comment]
Right, i forgot to filter local when online. I'll take care of both issues.

**Comment by deltakosh** [comment]
No worries I'll do a fix

We will reintroduce the feature when we will have more time ;)

**Comment by deltakosh** [comment]
Done

**Comment by RaananW** [comment]
The local version allows us to use the playground locally. We should filter it out or remove it when not in local mode, but removing it from the index.js breaks everything.

I'll take care of that tomorrow

**Comment by deltakosh** [comment]
It was a counter measure to stop the bleeding

**Comment by RaananW** [comment]
I believe it can be closed. Unless there is still an issue in the life playground
