### ISSUE TITLE
BabylonJS Editor not working

### ISSUE THREAD

**Issue by Gpinchon** [BabylonJS/Babylon.js#601]
Hi there,
I'm working on a scene exported from Unity 5, and I'm having an issue with the online editor located here : http://www.babylonjs.com/editor/
I'm trying to find an easy way to edit the .babylon file (as the scene is not correctly exported and looks really ugly).
I can successfully import my scene there : http://www.babylonjs.com/sandbox/
But I can't import it in the editor, as it's throwing me something about babylon.js, saying that "isInFrustrum" can not be read on an undefined object...
Before you ask, I can't share the .babylon file.

**Comment by Temechon** [comment]
Hello, 
It will be difficult to investigate without the babylon file... But I can already say that if it's working in the sandbox, the editor is the problem here. The Unity exporter uses the last version of Babylon, and I'm sure the editor is not using the same.
Can you at least share the whole stacktrace of the error you have in the console ? 
Thanks.

**Comment by RaananW** [comment]
The editor is using a very old version of the framework. This is probably a bug that was already fixed.

**Comment by davrous** [comment]
I'm going to try to update the editor to use the last version of babylon.js. The problem is that it could break the editor itself as it has some dependencies on the previous version of babylon.js as far as I remember. Will test that today and let you know.

**Comment by Gpinchon** [comment]
Little update, I tried exporting my scene from Blender, as the exporter is a lot better with Blender and allows me to craft my scene, do some texturing and great materials, and export them as they look in Blender to BabylonJS. However, I still have some small issues, like a light not displaying specular on objects around it (I can't get both a shadow and a specular map, and I would like to see in the editor how this light is configured once loaded, as it seems to be properly configured in the .babylon file)...

Now when I try to import my scene to the Editor, it's throwing me a 404 error, saying it couldn't find http://www.babylonjs.com/editor/null (but it could be related to the ongoing update ?), it's also telling me that undefined is not a function on line 2895 in Babylon.js.

**Comment by davrous** [comment]
I've just updated the editor by referencing v1.13 (we're currently 2.2beta) as this is the only version that seems to not break everything in the editor. 

You can now drag'n'drop a Unity scene into the Editor. 

Please note that this Editor was a project created by one of our intern and it's not maintained anymore. Please rather use our official sandbox tool with the debug layer, it's much more stable & upt to date.

**Comment by deltakosh** [comment]
I won't support this editor anymore. But you can still use this one if you want: https://github.com/BabylonJS/Editor

**Comment by julien-moreau** [comment]
Or use directly http://reath.free.fr/babylon to use the editor Deltakosh mentionned
