### ISSUE TITLE
The center of mass computation for compound objects differ according to the chosen physics plugin 

### ISSUE THREAD

**Issue by fabienrohrer** [BabylonJS/Babylon.js#8889]
When creating compound impostors, the center of mass seems to be computed as following:
- Ammo/Cannon: the center of the compound object (which is more or less useless, unless we could access to a `setCenterOfMass()` function, and even so it is difficult to compute it unless to have a magic `computeAutomaticCenterOfMass()` function which is often implemented in physics engines.)
- Oimo: the actual center of mass of the computed objects (which is much more useful, but the computation seems wrong, because the center of mass should depend on the mass distribution between objects while masses are not given to the sub meshes).

This issue is visible and easily reproductible when changing the colliders of the [third playground example](https://www.babylonjs-playground.com/#492ZK0#8) of the [compound body page](https://doc.babylonjs.com/how_to/compounds) (in this case, Oimo acts differently but more logically than Ammo and Cannon):

```js
// Add colliders
var bodyVisible = true;
var sphere = BABYLON.MeshBuilder.CreateSphere("sphere1", {diameter: 0.5}, scene);
sphere.position.y = 0.08;
sphere.isVisible = bodyVisible;
var box = BABYLON.MeshBuilder.CreateBox("box1", {size:0.2}, scene);
box.position.y = 0;
box.position.z = -0.4;
box.isVisible = bodyVisible;
```

**Comment by sebavan** [comment]
Adding @RaananW and @CedricGuillemet but it is expected for some feature that they all do not behave in the same way. 

Would be great if you could use the forum first to start the discussion.

**Comment by CedricGuillemet** [comment]
Hey @fabienrohrer I checked this issue and it looks like it's been fixed by @RaananW 's change on compound. Can you please confirm ?

**Comment by fabienrohrer** [comment]
Hey, sorry for the delay.
I follow this from far, but I think @RaananW fix issues related with the scaling on compound objects (thank you for this!). Nothing changed about the center of mass. I confirm that the original mismatch I mention here is still present in the example.

But... I also investigate from my side, and I think that my request is very difficult to solve. AmmoJS (and Bullet) does not provide any method to compute center of mass, or even to change it. It's the origin of the body of the compound object, period.
So I guess it's difficult to go ahead until to write a high level function to compute the center of mass based on the impostors (this is feasible, I have wrote this in my app), and to shift all the object centers with a lot of consequences.

If choice would be mine, I would document the fact that the center of mass is at the origin of the compound object, and fix Oimo to do the same for consistency reasons.

**Comment by CedricGuillemet** [comment]
Documentation updated : https://github.com/BabylonJS/Documentation/pull/2060 Closing.
